version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
clone_folder: c:\projects\infusion
init:
- git config --global core.autocrlf false
before_build:
- cmd: >-
    git submodule update --init --recursive
    nuget restore
    
build:
  project: Infusion.sln
  verbosity: minimal